// ============================================================
//  Philippines Jobs Portal — 10 Lakh (1,000,000) Job Pages
//  Country: Philippines | Schema: JobPosting JSON-LD
// ============================================================

const COUNTRY = {
  name: "Philippines",
  sameAs: "https://en.wikipedia.org/wiki/Philippines",
  addressCountry: "PH",
};

// ─── ALL COMPANIES (1,000 jobs each = 1,000,000 total) ───────────────────────
const COMPANIES = [
  // User-specified companies
  "Netflix",
  "Delta Airlines",
  "Southwest Airlines",
  "American Airlines",
  "Tesla",
  "Apple",
  "Amazon",
  "Google",
  "Disney",
  "United Airlines",
  "Wayfair",
  "Starbucks",
  "Walmart",
  "American Express",
  "Walgreens",
  "CostCo",
  "Wells Fargo",
  "Aetna",
  "Twitter",
  "PepsiCo",
  "Spirit Airlines",
  "CVS",
  "Hobby Lobby",
  "Home Depot",
  "Target",
  "Yelp",
  "Crocs",
  "Xbox",
  "Dell",
  "Anthem",
  "Sam's Club",
  "LabCorp",
  "TTEC",
  "Polaris",
  "UCHealth",
  "Smith and Wesson",
  "Hulu",
  "NDT",
  "CrunchyRoll",
  "Eddie Bauer",
  "USPC",
  "JetBlue Airlines",
  "UPS",
  "Chewy",
  "Alaska Airlines",
  "Allegiant Air",
  "Avelo Airlines",
  "Breeze Airways",
  "Eastern Airlines",
  "Frontier Airlines",
  "Hawaiian Airlines",
  "Sun Country Airlines",
  // Additional companies to reach 1,000,000 total
  "Microsoft",
  "Meta",
  "Uber",
  "Lyft",
  "Airbnb",
  "Shopify",
  "Salesforce",
  "Adobe",
  "Zoom",
  "Slack",
  "Spotify",
  "Twitch",
  "Pinterest",
  "Snapchat",
  "LinkedIn",
  "PayPal",
  "Square",
  "Stripe",
  "Robinhood",
  "Coinbase",
  "DoorDash",
  "Instacart",
  "Grubhub",
  "Postmates",
  "Lyft",
  "TaskRabbit",
  "Fiverr",
  "Upwork",
  "Freelancer",
  "Toptal",
  "HubSpot",
  "Zendesk",
  "Intercom",
  "Mailchimp",
  "Twilio",
  "Cloudflare",
  "Okta",
  "Datadog",
  "New Relic",
  "Splunk",
  "ServiceNow",
  "Workday",
  "Oracle",
  "SAP",
  "IBM",
  "Accenture",
  "Deloitte",
  "PwC",
  "KPMG",
  "EY",
  "McKinsey",
  "Bain",
  "BCG",
  "Infosys",
  "Wipro",
  "TCS",
  "Cognizant",
  "Capgemini",
  "Atos",
  "Tata",
  "HCL",
  "Tech Mahindra",
  "Mphasis",
  "Hexaware",
  "Mindtree",
  "L&T Infotech",
  "Mastech",
  "iGate",
  "Syntel",
  "NIIT Technologies",
  "Firstsource",
  "EXL Service",
  "WNS",
  "Genpact",
  "Sutherland",
  "iEnergizer",
  "Teleperformance",
  "Concentrix",
  "Conduent",
  "Convergys",
  "Alorica",
  "SITEL",
  "Synnex",
  "Arvato",
  "Capita",
  "Atento",
  "CSC",
  "Transcom",
  "StarTek",
  "Intelenet",
  "Hinduja Global",
  "Manulife",
  "Cigna",
  "Humana",
  "Blue Cross",
  "Kaiser Permanente",
  "UnitedHealth",
  "Centene",
  "Molina Healthcare",
  "Anthem BCBS",
  "CVS Aetna",
  "Johnson & Johnson",
  "Pfizer",
  "AbbVie",
  "Merck",
  "Bristol-Myers Squibb",
  "Gilead Sciences",
  "Biogen",
  "Regeneron",
  "Moderna",
  "BioNTech",
  "Novartis",
  "Roche",
  "AstraZeneca",
  "GlaxoSmithKline",
  "Sanofi",
  "Bayer",
  // Tech & Software
  "Atlassian",
  "Asana",
  "Monday.com",
  "Notion",
  "Airtable",
  "Figma",
  "Canva",
  "InVision",
  "Sketch",
  "Zeplin",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "CircleCI",
  "Travis CI",
  "Jenkins",
  "Docker",
  "Kubernetes",
  "HashiCorp",
  "Terraform",
  "Ansible",
  "Puppet",
  "Chef",
  "Vagrant",
  "VMware",
  "Citrix",
  "Nutanix",
  "Pure Storage",
  "NetApp",
  "Dell EMC",
  "HPE",
  "Lenovo",
  "Asus",
  "Acer",
  "Sony",
  "Samsung",
  "LG",
  "Panasonic",
  "Toshiba",
  "Fujitsu",
  "NEC",
  "Hitachi",
  "Epson",
  "Canon",
  "Nikon",
  "Olympus",
  "Leica",
  "GoPro",
  "DJI",
  "Logitech",
  "Razer",
  "Corsair",
  "HyperX",
  "SteelSeries",
  "Alienware",
  "MSI",
  "Gigabyte",
  "EVGA",
  "ZOTAC",
  "PNY",
  "Kingston",
  "Crucial",
  "Western Digital",
  "Seagate",
  "Toshiba Storage",
  "SanDisk",
  "Lexar",
  "Transcend",
  // E-commerce & Retail
  "Etsy",
  "eBay",
  "Alibaba",
  "AliExpress",
  "Wish",
  "Temu",
  "Shein",
  "ASOS",
  "Zara",
  "H&M",
  "Uniqlo",
  "Gap",
  "Old Navy",
  "Banana Republic",
  "J.Crew",
  "Anthropologie",
  "Urban Outfitters",
  "Free People",
  "Nordstrom",
  "Macy's",
  "Bloomingdale's",
  "Saks Fifth Avenue",
  "Neiman Marcus",
  "Barneys",
  "Kohl's",
  "JCPenney",
  "Sears",
  "TJX",
  "TJ Maxx",
  "Marshalls",
  "HomeGoods",
  "Burlington",
  "Ross Stores",
  "Five Below",
  "Dollar Tree",
  "Dollar General",
  "Family Dollar",
  "Big Lots",
  "Bed Bath & Beyond",
  "Williams-Sonoma",
  "Crate & Barrel",
  "West Elm",
  "Pottery Barn",
  "IKEA",
  "Ashley Furniture",
  "Rooms To Go",
  "La-Z-Boy",
  "Haverty's",
  "Bob's Discount Furniture",
  // Food & Beverage
  "McDonald's",
  "Burger King",
  "Wendy's",
  "Chick-fil-A",
  "Taco Bell",
  "Chipotle",
  "Panera Bread",
  "Subway",
  "Dunkin",
  "Tim Hortons",
  "Krispy Kreme",
  "Peet's Coffee",
  "Dutch Bros",
  "Shake Shack",
  "Five Guys",
  "In-N-Out",
  "Whataburger",
  "Jack in the Box",
  "Sonic",
  "Dairy Queen",
  "Baskin-Robbins",
  "Cold Stone Creamery",
  "Denny's",
  "IHOP",
  "Applebee's",
  "Chili's",
  "TGI Fridays",
  "Olive Garden",
  "Red Lobster",
  "Outback Steakhouse",
  "Cheesecake Factory",
  "PF Chang's",
  "Buffalo Wild Wings",
  "Domino's",
  "Pizza Hut",
  "Papa John's",
  "Little Caesars",
  "Papa Murphy's",
  "Round Table Pizza",
  "California Pizza Kitchen",
  // Finance & Banking
  "JPMorgan Chase",
  "Bank of America",
  "Citigroup",
  "Goldman Sachs",
  "Morgan Stanley",
  "Merrill Lynch",
  "Charles Schwab",
  "Fidelity",
  "Vanguard",
  "BlackRock",
  "State Street",
  "T. Rowe Price",
  "Raymond James",
  "Edward Jones",
  "LPL Financial",
  "Ameriprise Financial",
  "Northwestern Mutual",
  "New York Life",
  "MetLife",
  "Prudential",
  "Principal Financial",
  "Lincoln National",
  "Transamerica",
  "Sun Life",
  "Great-West Life",
  "Aflac",
  "USAA",
  "Allstate",
  "State Farm",
  "GEICO",
  "Progressive",
  "Farmers Insurance",
  "Liberty Mutual",
  "Travelers",
  "Nationwide",
  "Hartford",
  "Zurich",
  "Chubb",
  "AIG",
  "Markel",
  // Healthcare & Medical
  "Mayo Clinic",
  "Cleveland Clinic",
  "Johns Hopkins",
  "HCA Healthcare",
  "Tenet Healthcare",
  "Community Health Systems",
  "LifePoint Health",
  "Prime Healthcare",
  "Steward Health Care",
  "Ascension Health",
  "CommonSpirit Health",
  "Trinity Health",
  "Dignity Health",
  "Advocate Aurora Health",
  "Atrium Health",
  "Banner Health",
  "Northwell Health",
  "NewYork-Presbyterian",
  "Cedars-Sinai",
  "UCLA Health",
  "Stanford Health",
  "UCSF Health",
  "Mass General Brigham",
  "Beth Israel Lahey",
  "Yale New Haven",
  "Ochsner Health",
  "Intermountain Health",
  "SSM Health",
  "Mercy Health",
  "Bon Secours",
  "Franciscan Health",
  "Providence Health",
  "PeaceHealth",
  "MultiCare Health",
  "Virginia Mason",
  "OhioHealth",
  "Kettering Health",
  "Premier Health",
  "Summa Health",
  "Aultman Health",
  // Logistics & Transportation
  "FedEx",
  "DHL",
  "TNT",
  "XPO Logistics",
  "C.H. Robinson",
  "J.B. Hunt",
  "Werner Enterprises",
  "Schneider National",
  "Landstar System",
  "Old Dominion",
  "YRC Freight",
  "ABF Freight",
  "Estes Express",
  "Saia",
  "Southeastern Freight",
  "Forward Air",
  "Echo Global Logistics",
  "Coyote Logistics",
  "GlobalTranz",
  "Mode Transportation",
  "MoLo Solutions",
  "Arrive Logistics",
  "Transplace",
  "Worldwide Express",
  "Radiant Logistics",
  "nChannel",
  "Shipwire",
  "ShipBob",
  "Deliverr",
  "ShipStation",
  "ShipHero",
  "EasyPost",
  "Shippo",
  "Pirateship",
  "Stamps.com",
  "Endicia",
  "Pitney Bowes",
  "Neopost",
  "Hasler",
  "Francotyp-Postalia",
  // Media & Entertainment
  "Warner Bros",
  "Universal Pictures",
  "Paramount",
  "Sony Pictures",
  "Lionsgate",
  "MGM",
  "A24",
  "Blumhouse",
  "Focus Features",
  "IFC Films",
  "Magnolia Pictures",
  "NEON",
  "Amazon Studios",
  "Apple TV+",
  "HBO",
  "Showtime",
  "Starz",
  "AMC Networks",
  "FX Networks",
  "National Geographic",
  "Discovery",
  "Scripps Networks",
  "NBCUniversal",
  "CBS",
  "ABC",
  "Fox Corporation",
  "The CW",
  "BET",
  "MTV",
  "VH1",
  "Comedy Central",
  "Nickelodeon",
  "Cartoon Network",
  "Adult Swim",
  "Boomerang",
  "CNN",
  "MSNBC",
  "Fox News",
  "BBC",
  "Sky News",
  "Al Jazeera",
  "Reuters",
  "AP News",
  "Bloomberg",
  "The New York Times",
  "The Washington Post",
  "The Wall Street Journal",
  "USA Today",
  "Forbes",
  "Business Insider",
  "TechCrunch",
  "Wired",
  "The Verge",
  "Engadget",
  "Mashable",
  "BuzzFeed",
  "Vice Media",
  "Vox Media",
  "Condé Nast",
  "Hearst",
  "Meredith",
  "Time Inc",
  // Education & EdTech
  "Coursera",
  "Udemy",
  "edX",
  "Skillshare",
  "LinkedIn Learning",
  "Khan Academy",
  "Chegg",
  "Course Hero",
  "Quizlet",
  "Duolingo",
  "Rosetta Stone",
  "Babbel",
  "Pimsleur",
  "italki",
  "Preply",
  "Cambly",
  "VIPKID",
  "TutorMe",
  "Wyzant",
  "Tutor.com",
  "Varsity Tutors",
  "Revolution Prep",
  "The Princeton Review",
  "Kaplan",
  "Barron's",
  "Peterson's",
  "CollegeBoard",
  "ACT",
  "Educational Testing Service",
  "Pearson Education",
  "McGraw-Hill",
  "Cengage",
  "Houghton Mifflin",
  "Scholastic",
  "Random House",
  "Penguin Random House",
  "Simon & Schuster",
  "HarperCollins",
  "Macmillan Publishers",
  "Hachette Book Group",
  "Wiley",
  "Springer",
  "Elsevier",
  "Oxford University Press",
  "Cambridge University Press",
  "MIT Press",
  "Stanford University Press",
  // BPO & Call Centers
  "Accenture Philippines",
  "IBM Philippines",
  "Cognizant Philippines",
  "Infosys BPM",
  "Wipro BPS",
  "HCL BPO",
  "Mphasis BPO",
  "EXL Service Philippines",
  "WNS Philippines",
  "Genpact Philippines",
  "Sutherland Global",
  "iEnergizer Philippines",
  "Teleperformance PH",
  "Concentrix Philippines",
  "Conduent Philippines",
  "Alorica Philippines",
  "SITEL Philippines",
  "Transcom Philippines",
  "StarTek Philippines",
  "TaskUs",
  "Majorel",
  "Webhelp",
  "Hinduja Global Philippines",
  "Firstsource Philippines",
  "Intelenet Global",
  "Sykes Asia",
  "Convergys Philippines",
  "SPi Global",
  "Bounteous",
  "SupportNinja",
  "Wing",
  "Magic",
  "Outsource Accelerator",
  "Remote Staff",
  "Staff Domain",
  "CloudStaff",
  "ConnectOS",
  "Boldr.",
  "Booth & Partners",
  "MicroSourcing",
  "Sourcefit",
  "Offshore Business Processing",
  "Acquire BPO",
  "Probe CX",
  "Stellar",
  "Ariba",
  "Auxilio",
  "Callbox",
  "Magellan Solutions",
  "Innodata",
  "Integreon",
  "Ricoh Philippines",
  "Xerox Philippines",
  "Pitney Bowes PH",
  "Iron Mountain",
  "Recall Holdings",
  "GRM Document Management",
  "Access",
  "Corodata",
  "Vaultas",
  "DataBank",
  "Flexential",
  "Latisys",
  "CyrusOne",
  "QTS Data Centers",
  "Switch",
  "Aligned",
  "NTT Data",
  "Fujitsu Philippines",
  "NEC Philippines",
  "Hitachi Consulting",
  "Tata Consultancy Philippines",
  "Capgemini Philippines",
  "Atos Philippines",
  "CGI",
  "DXC Technology",
  "Unisys",
  "Leidos",
  "SAIC",
  "ManTech",
  "Booz Allen Hamilton",
  "CACI International",
  "Maximus",
  "CSRA",
  "PAE",
  "Engility",
  "KEYW",
  "KeyW",
  "Alion Science",
  "Battelle",
  "SRI International",
  "Mitre Corporation",
  "Aerospace Corporation",
  "IDA",
  "RAND Corporation",
  "Urban Institute",
  "Brookings",
  "Pew Research",
  "Gallup",
  "Nielsen",
  "IRI",
  "Kantar",
  "Ipsos",
  "Forrester Research",
  "Gartner",
  "IDC",
  "451 Research",
  "Current Analysis",
  "S&P Global",
  "Moody's",
  "Fitch Ratings",
  "DBRS",
  "AM Best",
  "Dun & Bradstreet",
  "Equifax",
  "Experian",
  "TransUnion",
  "Verisk Analytics",
  "CoreLogic",
  "Black Knight",
  "ICE Mortgage Technology",
  "Ellie Mae",
  "Blend",
  "Better.com",
  "Rocket Mortgage",
  "loanDepot",
  "United Wholesale Mortgage",
  "Guaranteed Rate",
  "Fairway Independent",
  "Movement Mortgage",
  "CrossCountry Mortgage",
  "PennyMac",
  "Freedom Mortgage",
  "Caliber Home Loans",
  "New American Funding",
  "LoanCare",
  "Mr. Cooper",
  "Nationstar Mortgage",
  "Ocwen Financial",
  "PHH Mortgage",
  "Shellpoint Mortgage",
  "ServiceMac",
  "Cenlar",
  "First American",
  "Fidelity National Financial",
  "Old Republic",
  "Stewart Information Services",
  "Investors Title",
  "WFG National Title",
  "Doma",
  "States Title",
  "Endpoint Closing",
  "Qualia",
  "SoftPro",
  "Resware",
  "RamQuest",
  "E-Closing",
  "Pavaso",
  "DocMagic",
  "Snapdocs",
  "NotaryCam",
  "Notarize",
  "Proof",
  "PandaDoc",
  "DocuSign",
  "Adobe Sign",
  "HelloSign",
  "SignNow",
  "RightSignature",
  "eversign",
  "Signaturely",
  "GetAccept",
  "Proposify",
  "Better Proposals",
  "Qwilr",
  "Bidsketch",
  "Nusii",
  "Practice Ignition",
  "Ignition",
  "Bonsai",
  "Honeybook",
  "Dubsado",
  "17hats",
  "ShootProof",
  "Pixieset",
  "CloudSpot",
  "Pic-Time",
  "Sprout Studio",
  "Studio Ninja",
  "Táve",
  "Light Blue",
  "Iris Works",
  "Bloom",
  "Aisle Planner",
  "WeddingWire",
  "The Knot",
  "Zola",
  "Joy",
  "Minted",
  "Artifact Uprising",
  "Chatbooks",
  "Shutterfly",
  "Snapfish",
  "Walgreens Photo",
  "CVS Photo",
  "Costco Photo",
  "Sam's Club Photo",
  "Walmart Photo",
  "Target Photo",
  "Mpix",
  "Nations Photo Lab",
  "Miller's Professional Imaging",
  "WHCC",
  "Bay Photo Lab",
  "ProDPI",
  "Loxley Colour",
  "Photobox",
  "Albelli",
  "Saal Digital",
  "Printful",
  "Printify",
  "Gooten",
  "Apliiq",
  "CustomCat",
  "Zazzle",
  "CafePress",
  "Society6",
  "Redbubble",
  "Merch by Amazon",
  "Spring (Formerly Teespring)",
  "Bonfire",
  "Represent",
  "Threadless",
  "Design By Humans",
  "Teepublic",
  "SunFrog",
  "ViralStyle",
  "LaunchCart",
  "Spreadshirt",
  "T-shirt Gang",
  "Printavo",
  "InkSoft",
  "DecoNetwork",
  "Printlogic",
  "ShipRobot",
  "OrderDesk",
  "Linnworks",
  "Skubana",
  "Brightpearl",
  "Cin7",
  "TradeGecko",
  "inFlow Inventory",
  "Fishbowl",
  "NetSuite WMS",
  "Manhattan Associates",
  "Blue Yonder",
  "HighJump",
  "Körber",
  "Infor WMS",
  "3PL Central",
  "Ware2Go",
  "Flexe",
  "STORD",
  "Flowspace",
  "Whitebox",
  "Whiplash",
  "ShipMonk",
  "Rakuten Super Logistics",
  "Quiet Platforms",
  "ShipBob PH",
  "Red Stag Fulfillment",
  "FulfillmentByService",
  "eFulfillment Service",
  "Moulton Logistics",
  "Verde Fulfillment",
  "Greenfield Global Logistics",
  "National Fulfillment Services",
  "AMSCAN",
  "Party City",
  "Spirit Halloween",
  "Spirit Christmas",
  "Halloween Express",
  "Fun Express",
  "Oriental Trading",
  "SmileMakers",
  "S&S Worldwide",
  "Stumps Prom",
  "Anderson's",
  "Windy City Novelties",
  "BirthdayExpress",
  "Birthday in a Box",
  "Shindig Parties",
  "Balloon Decor",
  "Zurchers",
  "Party Depot",
  "Balloon Time",
  "Pioneer Balloon",
  "Qualatex",
  "Anagram International",
  "CTI Industries",
  "Betallatex",
  "Sempertex",
  "Latex Occidental",
  "Belbal",
  "Amscan Holdings",
  "1-800-Flowers",
  "FTD",
  "Teleflora",
  "ProFlowers",
  "FromYouFlowers",
  "Bouqs",
  "UrbanStems",
  "Farmgirl Flowers",
  "BloomNation",
  "Flowwow",
  "Petal Republic",
  "Ode à la Rose",
  "Venus et Fleur",
  "Enjoy Flowers",
  "H.Bloom",
  "BloomThat",
  "Bloom & Wild",
  "Patch Plants",
  "The Sill",
  "Bloomscape",
  "Léon & George",
  "Greenery NYC",
  "Terrain",
  "Plant Therapy",
  "Mountain Rose Herbs",
  "Starwest Botanicals",
  "Frontier Co-op",
  "Simply Organic",
  "Organic India",
  "Gaia Herbs",
  "Herb Pharm",
  "Nature's Answer",
  "Solaray",
  "Jarrow Formulas",
  "Solgar",
  "Life Extension",
  "Thorne Research",
  "Pure Encapsulations",
  "Integrative Therapeutics",
  "Douglas Laboratories",
  "Metagenics",
  "Standard Process",
  "MediHerb",
  "Designs for Health",
  "Biotics Research",
  "Nutraceutix",
  "Country Life Vitamins",
  "American Health",
  "Mason Natural",
  "21st Century",
  "Vitacost",
  "iHerb",
  "Swanson Health",
  "NOW Foods",
  "Nature Made",
  "Nature's Bounty",
  "One A Day",
  "Centrum",
  "Flintstones",
  "Gummies",
  "OLLY",
  "Ritual",
  "Care/of",
  "HUM Nutrition",
  "SmartyPants",
  "MaryRuth Organics",
  "Garden of Life",
  "Rainbow Light",
  "New Chapter",
  "Megafood",
  "Whole Earth",
  "GNC",
  "Vitamin Shoppe",
  "Rite Aid",
  "Albertsons",
  "Kroger",
  "Safeway",
  "Publix",
  "H-E-B",
  "Meijer",
  "Hy-Vee",
  "Wakefern",
  "SpartanNash",
  "Weis Markets",
  "Ingles Markets",
  "Raley's",
  "WinCo Foods",
  "Stater Bros",
  "Grocery Outlet",
  "Aldi",
  "Lidl",
  "Trader Joe's",
  "Whole Foods",
  "Sprouts",
  "Natural Grocers",
  "Earth Fare",
  "Fresh Market",
  "Wegmans",
  "Giant Food",
  "Stop & Shop",
  "Shaw's",
  "Star Market",
  "Hannaford",
  "Price Chopper",
  "Market Basket",
  "Demoulas",
  "Big Y",
  "Tops Markets",
  "Price Rite",
  "C-Town",
  "Compare Foods",
  "Associated Food Stores",
  "Coborn's",
  "Country Mart",
  "Dan's Supermarkets",
  "Fareway",
  "Food4Less",
  "FoodMaxx",
  "Foods Co",
  "Fresh & Easy",
  "Fry's Food",
  "Giant Eagle",
  "Harris Teeter",
  "Jewel-Osco",
  "King Soopers",
  "Mariano's",
  "Martin's Food Markets",
  "Metro Market",
  "Pavilions",
  "Pick 'n Save",
  "Quality Food Centers",
  "Randalls",
  "Ralphs",
  "Smith's Food",
  "Tom Thumb",
  "Von's",
  "Acme Markets",
  "Baker's",
  "Ballfields",
  "Cambourne",
];

// 1,000 jobs per company = 1,000,000 total
const JOBS_PER_COMPANY = 1000;
const TOTAL_JOBS = COMPANIES.length * JOBS_PER_COMPANY;

// ─── PHILIPPINE CITIES / LOCATIONS ───────────────────────────────────────────
const PH_CITIES = [
  "Manila",
  "Quezon City",
  "Cebu City",
  "Davao City",
  "Makati",
  "Pasig",
  "Taguig",
  "Mandaluyong",
  "Pasay",
  "Caloocan",
  "Marikina",
  "Muntinlupa",
  "Parañaque",
  "Las Piñas",
  "Valenzuela",
  "Malabon",
  "Navotas",
  "San Juan",
  "Pateros",
  "Antipolo",
  "Bacoor",
  "Imus",
  "General Trias",
  "Dasmariñas",
  "San Pedro",
  "Biñan",
  "Santa Rosa",
  "Calamba",
  "Baguio",
  "Iloilo City",
  "Bacolod",
  "Cagayan de Oro",
  "Zamboanga City",
  "General Santos",
  "Lipa",
  "Batangas City",
  "Lucena",
  "Naga City",
  "Legazpi",
  "Tacloban",
  "Butuan",
  "Iligan",
  "Cotabato City",
];

// ─── SALARY RANGES (in PHP per month) ────────────────────────────────────────
const SALARY_RANGES = [
  { min: 25000, max: 35000 },
  { min: 35000, max: 50000 },
  { min: 50000, max: 75000 },
  { min: 75000, max: 100000 },
  { min: 100000, max: 150000 },
  { min: 150000, max: 200000 },
  { min: 200000, max: 300000 },
  { min: 25000, max: 45000 },
  { min: 40000, max: 60000 },
  { min: 60000, max: 90000 },
];

// ─── JOB TITLE TEMPLATES ─────────────────────────────────────────────────────
const TITLE_TEMPLATES = [
  "{company} Remote Jobs (Work From Home) {salMin} To {salMax}",
  "{company} Customer Support Jobs Work From Home",
  "{company} Data Entry Jobs Only - {salMin} To {salMax}/ Monthly",
  "{company} Work From Home Jobs - {salMin} To {salMax} Monthly Salary",
  "{company} Remote Customer Service Representative (Philippines)",
  "{company} Virtual Assistant Jobs Philippines {salMin}-{salMax}",
  "{company} Online Jobs Philippines - No Experience Required",
  "{company} Data Analyst Work From Home Jobs {salMin} To {salMax}",
  "{company} Remote Software Engineer Jobs Philippines 2025",
  "{company} Chat Support Agent Work From Home {salMin} To {salMax}",
  "{company} Social Media Manager Remote Jobs Philippines",
  "{company} Content Moderator Jobs Work From Home {salMin}",
  "{company} Remote Accounting Jobs Philippines - {salMin} To {salMax}",
  "{company} Night Shift Work From Home Jobs {salMin} To {salMax}",
  "{company} Part Time Remote Jobs Philippines {salMin} Monthly",
  "{company} Email Support Jobs Work From Home {salMin} To {salMax}",
  "{company} Remote Marketing Jobs Philippines {salMin} To {salMax}",
  "{company} Technical Support Specialist Work From Home",
  "{company} HR Remote Jobs Philippines {salMin} To {salMax} Monthly",
  "{company} Project Manager Work From Home Philippines {salMin}",
  "{company} Remote QA Tester Jobs Philippines {salMin} To {salMax}",
  "{company} Graphic Designer Work From Home {salMin} To {salMax}",
  "{company} Video Editor Remote Jobs Philippines {salMin} Monthly",
  "{company} Remote Sales Representative Philippines {salMin} To {salMax}",
  "{company} Transcriptionist Jobs Work From Home Philippines",
  "{company} Remote Business Analyst Jobs Philippines {salMin} To {salMax}",
  "{company} UI/UX Designer Work From Home Philippines {salMin}",
  "{company} Remote Product Manager Jobs Philippines {salMin} To {salMax}",
  "{company} Work From Home Admin Assistant Jobs Philippines",
  "{company} Remote Copywriter Jobs Philippines {salMin} To {salMax}",
  "{company} Telehealth Nurse Jobs Work From Home Philippines",
  "{company} Remote Financial Analyst Jobs Philippines {salMin} To {salMax}",
  "{company} Online Tutor Jobs Philippines {salMin} To {salMax} Monthly",
  "{company} Remote IT Support Jobs Philippines No Experience",
  "{company} Work From Home SEO Specialist Jobs Philippines {salMin}",
  "{company} Remote Legal Assistant Jobs Philippines {salMin} To {salMax}",
  "{company} Digital Marketing Specialist Work From Home {salMin}",
  "{company} Remote Bookkeeper Jobs Philippines {salMin} To {salMax}",
  "{company} Customer Success Manager Work From Home Philippines",
  "{company} Remote Operations Analyst Jobs Philippines {salMin} To {salMax}",
];

// ─── JOB DESCRIPTIONS ────────────────────────────────────────────────────────
const DESCRIPTIONS = [
  `Join our growing remote team! We are looking for talented individuals based in the Philippines to work with {company}. This is a fully remote position with competitive pay.

**What You'll Do:**
- Handle customer inquiries via email, chat, and phone
- Process data accurately and efficiently
- Coordinate with team members across different time zones
- Meet daily and weekly performance targets
- Provide excellent service to our global customers

**Requirements:**
- Strong English communication skills (written and verbal)
- Stable internet connection (minimum 10 Mbps)
- Dedicated workspace at home
- Computer or laptop (Windows 10 or Mac OS)
- Available to work full-time (40 hours/week)

**Benefits:**
- 100% Work From Home
- Health insurance (HMO)
- 13th month pay
- Paid leaves (vacation & sick)
- Internet allowance
- Equipment provided (after regularization)
- Career growth opportunities

Apply now and start your remote career with {company}!`,

  `{company} is hiring remote workers from the Philippines! No prior experience needed — full training provided. Start earning {salMin} to {salMax} PHP per month from the comfort of your home.

**Position Highlights:**
- Permanent work-from-home setup
- Fixed dayshift / midshift / nightshift schedules available
- Weekends off (depending on account)
- Regularization after 6 months
- Fast-track promotion for top performers

**Day-to-Day Tasks:**
- Respond to customer concerns promptly
- Document interactions in company CRM
- Escalate complex issues to senior agents
- Maintain quality scores above 95%
- Attend virtual team meetings and training

**Minimum Qualifications:**
- At least 18 years old
- High school diploma or equivalent
- Basic computer literacy
- Willing to work shifting schedules
- Has own laptop/desktop and reliable internet

**Compensation Package:**
- Basic Pay: {salMin} - {salMax} PHP/month
- Language allowance
- Performance incentives
- HMO on Day 1
- Life insurance`,

  `We are expanding our Philippines-based remote workforce at {company}! This is your chance to join a world-class company and build a rewarding career — all from home.

**About the Role:**
As part of our global team, you'll support operations, customers, or business functions depending on your department. Roles available in customer service, data operations, tech support, finance, HR, and more.

**Core Responsibilities:**
- Deliver high-quality output aligned with company standards
- Communicate effectively with clients and internal stakeholders
- Meet KPIs and performance metrics consistently
- Participate in continuous improvement initiatives
- Complete required trainings and certifications

**Who We're Looking For:**
- Motivated, self-starting individuals
- Excellent time management skills
- Proficiency in Microsoft Office / Google Suite
- Strong analytical and problem-solving skills
- Ability to work independently with minimal supervision

**Salary and Perks:**
- Monthly salary: {salMin} to {salMax} PHP
- Quarterly bonuses
- HMO for employee + 1 dependent
- Paid government-mandated benefits (SSS, PhilHealth, Pag-IBIG)
- Work equipment provided
- Professional development budget`,
];

// ─── EMPLOYMENT TYPES ────────────────────────────────────────────────────────
const EMPLOYMENT_TYPES = [
  "FULL_TIME",
  "PART_TIME",
  "CONTRACTOR",
  "FULL_TIME",
  "FULL_TIME",
  "FULL_TIME",
  "FULL_TIME",
  "CONTRACTOR",
];

// ─── DETERMINISTIC PSEUDO-RANDOM ─────────────────────────────────────────────
function seededRand(seed) {
  // Simple LCG
  let s = seed;
  return function () {
    s = (s * 1664525 + 1013904223) & 0xffffffff;
    return (s >>> 0) / 0xffffffff;
  };
}

function pick(arr, r) {
  return arr[Math.floor(r() * arr.length)];
}

// ─── CORE JOB GENERATOR ──────────────────────────────────────────────────────
function getJob(id) {
  if (id < 1 || id > TOTAL_JOBS) return null;

  const rand = seededRand(id * 2654435761);
  r = rand;

  // Which company does this job belong to?
  const companyIndex = Math.floor((id - 1) / JOBS_PER_COMPANY);
  const company = COMPANIES[companyIndex] || COMPANIES[id % COMPANIES.length];

  const salaryRange = pick(SALARY_RANGES, r);
  const salMin = salaryRange.min.toLocaleString();
  const salMax = salaryRange.max.toLocaleString();
  const city = pick(PH_CITIES, r);
  const isRemote = r() > 0.3; // 70% remote

  // Build title
  const titleTemplate = TITLE_TEMPLATES[(id - 1) % TITLE_TEMPLATES.length];
  const title = titleTemplate
    .replace(/{company}/g, company)
    .replace(/{salMin}/g, salMin)
    .replace(/{salMax}/g, salMax);

  // Build description
  const descTemplate = DESCRIPTIONS[(id - 1) % DESCRIPTIONS.length];
  const description = descTemplate
    .replace(/{company}/g, company)
    .replace(/{salMin}/g, salMin)
    .replace(/{salMax}/g, salMax);

  const employmentType = EMPLOYMENT_TYPES[(id - 1) % EMPLOYMENT_TYPES.length];

  // Date calculations
  const baseDate = new Date("2025-01-01");
  baseDate.setDate(baseDate.getDate() + Math.floor(r() * 365));
  const datePosted = baseDate.toISOString().split("T")[0];

  const validDate = new Date(baseDate);
  validDate.setDate(validDate.getDate() + 90);
  const validThrough = validDate.toISOString().split("T")[0];

  const schema = {
    "@context": "https://schema.org/",
    "@type": "JobPosting",
    title: title,
    description: description,
    datePosted: datePosted,
    validThrough: validThrough,
    employmentType: employmentType,
    hiringOrganization: {
      "@type": "Organization",
      name: company,
      sameAs: `https://www.${company.toLowerCase().replace(/\s+/g, "")}.com`,
    },
    jobLocation: isRemote
      ? {
          "@type": "Place",
          address: {
            "@type": "PostalAddress",
            addressLocality: city,
            addressCountry: COUNTRY.addressCountry,
          },
        }
      : {
          "@type": "Place",
          address: {
            "@type": "PostalAddress",
            addressLocality: city,
            addressRegion: "Philippines",
            addressCountry: COUNTRY.addressCountry,
          },
        },
    jobLocationType: isRemote ? "TELECOMMUTE" : undefined,
    applicantLocationRequirements: [
      {
        "@type": "Country",
        name: COUNTRY.name,
        sameAs: COUNTRY.sameAs,
      },
    ],
    baseSalary: {
      "@type": "MonetaryAmount",
      currency: "PHP",
      value: {
        "@type": "QuantitativeValue",
        minValue: salaryRange.min,
        maxValue: salaryRange.max,
        unitText: "MONTH",
      },
    },
  };

  // Remove undefined keys
  if (!isRemote) delete schema.jobLocationType;

  return {
    id,
    title,
    company,
    description,
    employmentType,
    datePosted,
    validThrough,
    salary: `₱${salMin} - ₱${salMax} / month`,
    location: isRemote ? `Remote (${city}, Philippines)` : `${city}, Philippines`,
    isRemote,
    city,
    schema,
  };
}

module.exports = {
  TOTAL_JOBS,
  COMPANIES,
  JOBS_PER_COMPANY,
  COUNTRY,
  PH_CITIES,
  getJob,
};
